runtime: python39  # or python311 if needed

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_USER: "root"
  DB_PASS: ""
  DB_NAME: "project5-db"
  DB_CONNECTION_NAME: "project5-456917:us-central1:project5-db"
  GOOGLE_APPLICATION_CREDENTIALS: "project5-456917-a2e052c206fe.json"

handlers:
- url: /media
  static_dir: media

- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: project5-456917:us-central1:project5-db
