runtime: nodejs20
instance_class: F1

handlers:
# Serve static assets (JS, CSS, images, etc.)
- url: /(.+\.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot|otf|map))$
  static_files: dist/\1
  upload: dist/.*

# Fallback to index.html for React Router
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html